### ISSUE TITLE
Document Installation via CLI

### ISSUE THREAD

**Issue by riazarbi** [3dcitydb/importer-exporter#99] opened 2019-09-11 13:56 UTC
The installation instructions for importer-exporter [here](https://3dcitydb-docs.readthedocs.io/en/latest/intro/install-impexp.html) and [here](http://www.3dcitydb.org/3dcitydb/fileadmin/downloaddata/3DCityDB_Documentation_v4.2.pdf) explain how to install the client by using the Universal Installer Package. These instructions depend on the existence of an interactive desktop environment. 

Since importer-exporter now supports `cli` mode, where you can use it in bash scripts, it is probable that a common emerging use case will be deployment of the importer-exporter in data pipelining jobs on servers with no desktop interface. 

Consequently, it would be great if this project could document the installation of this tool via the command line interface. 

It would be especially useful if a reference Dockerfile could be released that allows us to use an importer-exporter docker image in `exec` mode. For an example of this, see the minio `mc` [docker image](https://hub.docker.com/r/minio/mc), which behaves like a regular executable. 

This would enable users to embed importer-exporter functionality into workflows on job scheduling applications like Apache Airflow.

**Comment by FxKu** [comment] 2019-09-11 14:12
A Dockerfile example can be found [here](https://github.com/tum-gis/3dcitydb-docker-postgis).

Building / installation of the ImpExp via CLI is done with gradle. I thought we had it documented, but can't find it either now. So yes, we should include a chapter then.

**Comment by riazarbi** [comment] 2019-09-11 14:19
Does the 3dCityDB docker image include the ImpExp executable?

**Comment by FxKu** [comment] 2019-09-11 15:11
Not 100% sure. I thought we got Dockerfiles for all components :grinning: . @BWibo?

**Comment by BWibo** [comment] 2019-09-11 15:19
Hey there, 
yes, of course the image  includes the ImpExp executable. I haven't published the repo jet, as I didn't find time to complete the documentation jet. 
I will quickly add a note that this is work in progress and switch the repo to public.
You can find the Dockerfile here in a few minutes. 
[https://github.com/tum-gis/3dcitydb-importer-exporter-docker](https://github.com/tum-gis/3dcitydb-importer-exporter-docker)
If you have problems/need support please open an issue at this repo. Closing this, feel free to reopen if required.

**Comment by BWibo** [comment] 2019-09-11 15:42
Re-opening, as the documentation issue remains.

**Comment by riazarbi** [comment] 2019-09-12 07:47
Thank you @BWibo.

**Comment by EricBoix** [comment] 2020-01-10 12:27
Thanks a lot @BWibo for the docker image. You made my week ! 

When in need of scripting (CLI) some usage of the ImporterExporter I naively tried to transpose the usage of [JAR installer](https://3dcitydb-docs.readthedocs.io/en/latest/intro/install-impexp.html) within a script. Although it looks like [IZPack allows for unattended installations using properties](https://izpack.atlassian.net/wiki/spaces/IZPACK/pages/491726) this proved beyond my technical reach. 

I then tried to start from the [sources (git repository)](https://github.com/3dcitydb/importer-exporter), lost quite some time (my recent java mileage is quite low) in understanding the [building instructions](https://github.com/3dcitydb/importer-exporter#building), but eventually I got lost in the details and was about to quit when I found this issue.

Hopefully [using your Docker image was straightforward](https://github.com/VCityTeam/UD-Reproducibility/blob/master/Computations/ComputeLyon3DTilesTemporal/ShellScriptCallingDocker/DockerLoad3dCityDataBase.sh#L40). I just wanted to provide some feedback on the usage I made of it (that might hopefully benefit to other un-experimented users?):
 - prior to using the dockerized importer the calling context has (at least I have) to regroup all the CityGML files to be [imported within a single directory](https://github.com/VCityTeam/UD-Reproducibility/blob/master/Computations/ComputeLyon3DTilesTemporal/ShellScriptCallingDocker/DockerLoad3dCityDataBase.sh#L45). This apparent usage constraint is of course not specific to 3dCityb-Importer docker container.
 - The calling context must store a full [importer full configuration file](https://github.com/VCityTeam/UD-Reproducibility/blob/master/Computations/ComputeLyon3DTilesTemporal/ShellScriptCallingDocker/3dCityDBImpExpConfig-2009.xml) that must be transmitted to the container when in the general usage case only a few parameters are needed i.e. the ones of the connection node as [documented at the item 3 entry of the usage documenttion](https://github.com/tum-gis/3dcitydb-importer-exporter-docker#usage). Those parameters generally match the one [set for the server](https://github.com/tum-gis/3dcitydb-docker-postgis#how-to-use-this-image). Maybe we could mimic the parameter syntax of the server for the importer and have the configuration file generated under the hood (by the container `entrypoint` script) on instantiation of the container ? Just my 2cts.

Anyhow thanks again  @BWibo.

**Comment by clausnagel** [comment] 2020-09-18 22:05
Closing because the installation via CLI is [documented](https://3dcitydb-docs.readthedocs.io/en/latest/intro/install-impexp.html) now. 

Thanks @EricBoix for the valuable input on enhancing the Docker images. I am not sure whether this discussion was continued with @BWibo outside this issue? We are planning to enhance the CLI of the Importer/Exporter soon and to provide more command-line parameters, for instance, for specifying the database connection details and to trigger default operations. So, provding a full configuration file should only be optional then.

**Closed by clausnagel** 2020-09-18 22:05 UTC

**Comment by EricBoix** [comment] 2020-09-28 14:12
Just to answer you question @clausnagel the discussion with @BWibo was not
pursued outside this issue since with the kindly provided information (mainly the Dockerfile)
we could get the job done (i.e. running scripts using the importer/exporter from Python and
within a Docker container).

As a side note, and in order to get things running from Python, we had to
 - generate the ad-hoc importer configuration file for which eventually [used the Jinja2 code generator](https://github.com/VCityTeam/UD-Reproducibility/blob/master/Computations/3DTiles/LyonTemporal/PythonCallingDocker/demo_load_3dcitydb.py#L25) 
 - [duplicate the Dockerfile in order to pinpoint](https://github.com/VCityTeam/UD-Reproducibility/blob/python-docker-static-tiler/Computations/3DTiles/LyonTemporal/Docker/3DCityDBImpExp-DockerContext/Dockerfile#L35) an "effective" (for us) version.

Anyhow we the above "tricks" things are now running except for some nasty (yet [well known](https://github.com/docker-library/postgres/issues/544)) side effect occurring when stopping the container (and leaving a broken database: the warning/error message goes `database system was not properly shut down; automatic recovery in progress`). But this is not specific to the Importer/exporter code but to docker/postgresql interactions...

**Comment by clausnagel** [comment] 2020-09-29 07:09
Thanks for your kind feedback, @EricBoix, and for pointing to your Jinja2 code generator. Cool stuff :-)

We are aware that requiring an XML config file to be able to use the CLI of the Importer/Exporter is not very user-friendly, especially in a Docker environment. As stated above, we want to rework the CLI so that it offers more parameters that allow for triggering imports and exports without the need for an additional config file. On the other hand, if we map every setting that is possible with the config file to separate command-line parameters, the list of parameters will be (too?) big.

So, we are currently looking for the most important parameters that support the most typical import and export scenarios. Feel free to contribute your requirements in this issue #139.
