### ISSUE TITLE
errors on exporting CityGML in 3D Database

### ISSUE THREAD

**Issue by benshuo** [3dcitydb/importer-exporter#57] opened 2018-11-02 16:04 UTC
Hi,
I use the 3DCityDB Importer Exporter tool to export my own CityGML data in the 3DCityDB database, but when the process finished, the FME Inspector show there is no geometry about the export file. I open the file with Notepad++(see figure 1), the right one should be figure 2. It looks like I miss some part during the process. I don't know which part is wrong, is the import part, the export part or the setup database part? Thanks for help
![image](https://user-images.githubusercontent.com/44577033/47926541-14928080-dec1-11e8-9889-0dae65b344af.png)
![image](https://user-images.githubusercontent.com/44577033/47926553-1fe5ac00-dec1-11e8-84e2-6d8b0b50d12f.png)

Kind regards,
Wang Benshuo

**Comment by clausnagel** [comment] 2018-11-02 16:45
Please provide (an excerpt of) your CityGML dataset, if possible, so that we can try and reproduce the issue.

**Comment by benshuo** [comment] 2018-11-03 11:58
[strijp-s.zip](https://github.com/3dcitydb/importer-exporter/files/2544923/strijp-s.zip)
thanks

**Comment by clausnagel** [comment] 2018-11-03 14:44
Ok, I did the following:

1. Set up a new 3DCityDB 4.0 using EPSG 28992
2. Imported your dataset strijp-s.xml
3. Exported the database content into a new file

I cannot reproduce your issue. I get all data exported correctly: [test.zip](https://github.com/3dcitydb/importer-exporter/files/2545042/test.zip)

Maybe you were using some filter settings on the CityGML export tab due to which no buildings were exported? Or did you receive any error messages during export?

Nevertheless, note that you CityGML dataset does not validate against the schema. Simply click the "Just validate" button on the CityGML import tab of the Importer/Exporter to get a list of the issues.

**Comment by benshuo** [comment] 2018-11-05 10:29
thanks, here is another problem, I want to turn the CityGML format to glTF, based on the document, I need to import CithGML and Export CityGML first. But when I export the glTF and open it with Google Earth, the location is nor right. When i import the test file and validate, it shows some errors. Therefore, are these errors cause the problem?  Thanks
![image](https://user-images.githubusercontent.com/44577033/47992728-eb0a6c80-e0ed-11e8-9d3d-474e63d0bf22.png)

**Comment by clausnagel** [comment] 2018-11-07 07:38
Well, did a KML/COLLADA export and loaded it into Google Earth. The position of the buildings looks fine.

![strijp-s](https://user-images.githubusercontent.com/5517439/48116467-89214280-e266-11e8-90f8-ab2c2a74bdbb.PNG)

@FxKu is right, I used EPSG:28992 to set up the database, simply because this reference system is used in your original dataset `strijp-s.xml`. Make sure to not mix up reference systems.

The validation errors are mostly due to incorrect `gml:id` values (in your case, a `gml:id` must not start with a number). The 3DCityDB can correctly handle the data. However, the error should be fixed in your data.

And there are a lot of falsely oriented polygons in your dataset. If you visualize it in Google Earth, it will look like these polygons are missing, which leaves holes in the buildings. You can force their visualization by checking `Ignore surface orientation` in the "Preferences -> KML/COLLADA/glTF Export -> Rendering -> Building" settings (which is what I did for the above screenshot). But again, this issue should be fixed in your data in the first place.

**Closed** 2018-12-22 11:33 UTC
