### ISSUE TITLE
Suggestions to improve ADE manager log messages

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#306] opened 2024-06-17 10:32 UTC
Dear 3DCityDB team,

While working with the ADE Manager, I encountered some cases where the ADE Manager simple stops/exits (due to possible errors in the XSD file) but it does not report anything. Hence my suggestion to improve messages to the user. So far I encountered:

- When the XSD contains multiple elements of the same name. Example: you extend multiple CityGML classes with an attribute named "area"), such as:

```
<element name="area" substitutionGroup="core:_GenericApplicationPropertyOfBuilding" type="gml:AreaType"/>
<element name="area" substitutionGroup="core:_GenericApplicationPropertyOfDoor" type="gml:AreaType"/>
<element name="area" substitutionGroup="core:_GenericApplicationPropertyOfWindow" type="gml:AreaType"/
```
- In case you want to extend a TINRelief class. Example:

`  <element name="area2" substitutionGroup="dem:_GenericApplicationPropertyOfTinRelief" type="gml:AreaType"/>`

- In case you want to extend a CityGML class using ImplicitGeometries (currently not supported, AFAIK).
`  <element name="lod0ImplicitRepresentation" substitutionGroup="veg:_GenericApplicationPropertyOfSolitaryVegetationObject" type="core:ImplicitGeometryType"/>
`

(I may edit and add more if I find them, even just for documentation for the ADE developers out there...)

Do you confirm?

G.

**Comment by clausnagel** [comment] 2024-06-17 10:45
All your examples are indeed invalid ADE XML schemas and need to be fixed. I agree that the ADE Manager should be more verbose in such cases. Can you share the schemas for testing?

**Comment by gioagu** [comment] 2024-06-17 10:52
Here you go :-)


[Test2_ADE.zip](https://github.com/user-attachments/files/15865990/Test2_ADE.zip)

**Comment by clausnagel** [comment] 2024-08-17 21:01
1. XML schema errors are now reported to the user with fix https://github.com/3dcitydb/plugin-ade-manager/commit/d7aa87699f87e6e3589f13768f9557556bbbb3cb.
2. For the TINRelief, an NPE was reported to the user due to an internal mapping error. This has also been fixed with https://github.com/3dcitydb/plugin-ade-manager/commit/1fbd9fa16367ed6b862f781fa6f38fdff0364999.
3. I couldn't reproduce the issue with your implicit geometry example. It is processed by the ADE Manager without stops or exists. However, if you really want to assign an implicit geometry through an ADE hook, use the property type "core:ImplicitRepresentationPropertyType" to conform with GML rules:
```xml
<element name="lod0ImplicitRepresentation" substitutionGroup="veg:_GenericApplicationPropertyOfSolitaryVegetationObject" type="core:ImplicitRepresentationPropertyType"/>
```

**Comment by clausnagel** [comment] 2024-09-19 12:52
Inlcuded as described in version 2.3.0 of the ADE Manager Plugin.

**Closed by clausnagel** 2024-09-19 12:52 UTC
Labels: enhancement
