### ISSUE TITLE
OSM Not Showing in "View/Open Map Window"

### ISSUE THREAD

**Issue by sschoenhardt** [3dcitydb/importer-exporter#97] opened 2019-07-09 14:36 UTC
Hello! I am new to this software and have been learning how to use it and set it up through 3D City DB's official documentation. The current issue I am having is that when I open the Map Window utility for selecting bounding boxes, the OpenStreetMaps visuals will not load, rendering the utility unusable.
![image](https://user-images.githubusercontent.com/52708510/60896861-14f3d000-a235-11e9-8afa-9dacb1f986c0.png)
The only potential fixes I have been able to find for this issue seem to require adjusting the proxy settings in the preferences. However, the company computer I am using this software on does not connect to the internet through a network proxy. Can anyone suggest any fixes or troubleshooting steps I can take? Thank you in advance!

**Comment by clausnagel** [comment] 2019-07-09 15:28
Thanks, @sschoenhardt. It is a known issue and has already been fixed (see https://github.com/3dcitydb/swingx-ws/commit/785aaa0122bccc007f45bc344ee187628427b2b5).

The fix will be included in the next release of the Importer/Exporter. If you need a working version earlier, then you can easily build it from the `master` branch following these steps: https://github.com/3dcitydb/importer-exporter#building

**Comment by sschoenhardt** [comment] 2019-07-09 15:30
@clausnagel Thank you so much!

**Comment by Itsman-AT** [comment] 2019-10-08 13:01
I am experiencing the same issue here. Will build from master as well. Thanks.

**Comment by santannamv** [comment] 2019-12-10 01:39
Thanks! I also built a new installer and the issue is gone. Just want to add that Grable requires Java's JDK and JRE running on the same version.

**Comment by clausnagel** [comment] 2020-04-06 16:10
Closing this issue since the fix is now included in the [4.2.3 release](https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3).

**Closed by clausnagel** 2020-04-06 16:10 UTC
