### ISSUE TITLE
Error while validating CityGML file in 3DCityDB

### ISSUE THREAD

**Issue by lorelos** [3dcitydb/importer-exporter#127] opened 2020-08-13 03:11 UTC
Hi,
I'm having trouble controling and importing a CityGML model with the importer/exporter tool. Here is the link for the .gml file and the error log I get.
- one "just validate" error;
- one import error;
I don't understand why this strange import is successfull.

https://drive.google.com/drive/folders/1-2rfkbW0JPPNFkdKMyeawfnxEsdIfjYc?usp=sharing

**Comment by clausnagel** [comment] 2020-08-13 06:41
Your CityGML dataset is invalid and does not comply with the [official CityGML 1.0 schemas](http://schemas.opengis.net/citygml/). Unless this is really what you want to do, you should not import invalid datasets but rather fix them before importing.

The log message `Database import successfully finished.` means that the import operation itself completed successfully and did not abort due to internal program errors. It does not mean that your data is clean. Import issues caused by your data are reported as warning and error messages during the import session.

**Comment by lorelos** [comment] 2020-08-13 21:45
Thank you. I'll clean the data and try again.
Regards

**Comment by clausnagel** [comment] 2020-09-18 19:52
Closing because this is a data issue but not an Importer/Exporter issue. Feel free to re-open if you need further assistance.

**Closed by clausnagel** 2020-09-18 19:52 UTC
Labels: question
