### ISSUE TITLE
Geometric invalidity in exported CityJSON files

### ISSUE THREAD

**Issue by ozgetufan** [3dcitydb/importer-exporter#245] opened 2022-03-09 09:20 UTC
Hello,

I imported a CityGML file using the 3DCityDB Importer-Exporter, which I then exported as a CityJSON file. While the CityGML file is valid (checked with FME, 3DCityDB, val3dity), the output CityJSON file seems to be invalid when it comes to the geometries. There are consecutive duplicate points in boundaries, and val3dity reported other errors as well (CONSECUTIVE_POINTS_SAME, RING_SELF_INTERSECTION, INTERSECTION_RINGS, etc).

Since the input CityGML file is valid, I thought maybe this problem would be related to the 3DCityDB Exporter. 

Thanks!

**Comment by clausnagel** [comment] 2022-03-09 14:45
Duplicate of https://github.com/citygml4j/citygml-tools/issues/27. As described there, increase the number of significant digits. This can be set under "Preferences -> Export -> CityJSON options -> Precision Coordinates". 

Check the [chapter 4.5.9.10 of the online user manual](https://3dcitydb-docs.readthedocs.io/en/version-2021.1/impexp/export-preferences/cityjson.html) and especially the "Caution" box.

**Closed** 2022-05-14 07:18 UTC
