### ISSUE TITLE
Export gives "NullPointerException"

### ISSUE THREAD

**Issue by AkiTuomaala** [3dcitydb/importer-exporter#118] opened 2020-04-30 15:13 UTC
Hi!

I've been trying to export data out from database, but im getting NullPointerException all the time.

Data inside imported is one of the samples in Importer_Exporter\samples\Berlin\CityGML\Gasometer_LoD2\
Data is imported inside without problem, but when trying to export it gives this exception?
Im not using any filters while exporting either..

Is there way to get more details about error?

I'm using 4.2.0 version of Importer/Exporter

**Comment by yaozhihang** [comment] 2020-05-07 09:24
Hi, which database (postgis or oracle), and which version of it are your using? 
Could you share a screenshot bild of the console window showing the NullPointerException?

**Comment by AkiTuomaala** [comment] 2020-05-07 13:11
Hi @yaozhihang !
Details what im using:

3DCityDB -> 
4.0.1 version

Database -> 
PostgreSQL  11.5
SRID:
urn:ogc:def:crs,crs:EPSG:6.12:3068,crs:EPSG:6.12:5783

Tutorial -> 
https://github.com/3dcitydb/tutorials/blob/master/3DCityDB_V4.0_Hands-On_Tutorial.pdf

Data what im trying to import:
\Importer_Exporter\samples\Berlin\CityGML\Gasometer_LoD2\Gasometer.zip

Validation ->
![Validation](https://user-images.githubusercontent.com/64587318/81297462-f3918980-907b-11ea-8aee-7f71f00aa551.PNG)

Import ->
![Import](https://user-images.githubusercontent.com/64587318/81297683-5125d600-907c-11ea-8cca-7316a2fb14d5.PNG)

Database report ->
![Database_report](https://user-images.githubusercontent.com/64587318/81297787-761a4900-907c-11ea-9278-ec607f9a8f9c.PNG)

Boundingbox calculation is never finished (I let it calculate 2h without result) ->
![Bounding_box_calculation](https://user-images.githubusercontent.com/64587318/81297879-a3ff8d80-907c-11ea-92cd-1691844ecead.PNG)

Export error ->
![Export_null](https://user-images.githubusercontent.com/64587318/81298353-57688200-907d-11ea-9279-a8df16da32b6.PNG)

**Comment by yaozhihang** [comment] 2020-05-07 13:31
Many thanks for sharing the info. It is a weird issue. Could you do a test with the newest version of the Importer/Exporter (v4.2.3) and 3DCityDB (v4.0.3)?
https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3

You may also change the logging level to `DEBUG` (see the screenshot below). The console window of the Importer/Exporter will hopely print out more details about the NullPointerException when it occurs again. 

![image](https://user-images.githubusercontent.com/5942971/81299954-56345680-9077-11ea-804e-d78c17233229.png)

**Comment by AkiTuomaala** [comment] 2020-05-07 19:40
Thank you @yaozhihang for your intrest on my case!

I installed v4.2.3 from link you send and installed everything from start. 
1. Dropped old database with **DROP_DB.bat**
2. Created new database with **CREATE_DB.bat**
SRID same like last time:
3068
Height system default (Tried also with 5783)
**urn:ogc:def:crs,crs:EPSG:6.12:3068,crs:EPSG:6.12:5783**
3. Made "log level" to DEBUG
4. Imported same data from samples **Gasometer_LoD2\Gasometer.zip**
5. Bonding box cannot be calculated still? (Is there anyway to check some log what import/export is processing while its calculating?)
6. Tried to export data, but have same error..
![Export_null_new_IE](https://user-images.githubusercontent.com/64587318/81337006-f8bdfb00-90b2-11ea-9430-fd92cc924d89.PNG)

Tried also with different log levels, but all give same error log?

Will tmr check inside code little too. If I could get inside little bit how importer / exporter is calculating bounding box. Its not so much data anyways. So maybe there something there?

**Comment by AkiTuomaala** [comment] 2020-05-08 13:26
Okay.. So figured it out.. My "environment variables" JAVA_PATH was showing to jdk... I guess I've forgotten to change it back to jre when I was working with other project..

**Comment by yaozhihang** [comment] 2020-05-08 13:48
Could you do the followings?: 
1. export the config file of your Importer/Exporter vir the the menubar button "Projeckt -> Save Project As..." 
2. remove your private information (e.g. DB connection password) from the exported config file
3. share the config file via this github channel, or send me via email zyao[at]virtualcitysystems.de

This config file will help me to quickly find out the issue cause. Thanks.

**Comment by AkiTuomaala** [comment] 2020-05-08 13:51
Hi @yaozhihang!
Thank you again. But it seems to work now like its suppose to. My JAVA_PATH was wrong and after changing it works like a charm :)

Thank you!

**Comment by clausnagel** [comment] 2020-05-08 13:59
Great to hear that you were able to fix the issue, @AkiTuomaala. Are you able to share some more information on what solved the issue? I am also using a JDK, and my `JAVA_HOME` is pointing to that JDK. Moreover, my `PATH` variable contains a reference to `JAVA_HOME/bin` as well.

With these settings, I have not experienced a similar issue like yours so far, and I guess using a JDK should work just fine. So, is there something else in your setting that might have caused the expection?

**Comment by AkiTuomaala** [comment] 2020-05-08 14:48
Hmm.. Well I also updated Postgresql from 11.5 -> 11.7
But I tried after that update to create export, but it gave me same null error..

Made my JAVA_HOME back to jdk and it stopped working. So there is something in there.. Will try to play around with java variables and will tell if something comes up.

**Comment by mulfvik** [comment] 2020-09-11 10:07
Hi, I am having a similar problem when running an export from shell. The same export runs well in the importer/exporter gui. The kmlExport runs well in both shell and gui. Have not tested the importer.
Tested with updated jre and jdk with same result. JAVA_HOME is set and the path aswell.
Any thougths on this? Have you come up with any @AkiTuomaala ?

![image](https://user-images.githubusercontent.com/24228538/92907269-7610c800-f425-11ea-9050-8aceb1719ba6.png)

**Comment by clausnagel** [comment] 2020-09-11 11:13
@mulfvik, can you please share your config file so that we can use it for testing? Please remove any database connection details and passwords beforehand.

**Comment by clausnagel** [comment] 2020-09-11 11:20
@mulfvik, well, I could easily reproduce your issue and it's a bug. Will fix it and let you know soon.

**Comment by clausnagel** [comment] 2020-09-11 12:14
@mulfvik, fixed in `master` (81692828ee52acfcdb611cb76e6681eafd0117ea). You can build a new Importer/Exporter from the `master` branch following [this short guideline](https://github.com/3dcitydb/importer-exporter#building).

**Comment by mulfvik** [comment] 2020-09-11 12:46
Thank you @clausnagel for this quick fix. Back on track.

**Comment by clausnagel** [comment] 2020-09-18 21:40
Closing this issue because adapting the JAVA_PATH variable fixed the initial problem.

**Closed by clausnagel** 2020-09-18 21:40 UTC
