### ISSUE TITLE
visualize 3d model on the 3dwebclient directly from 3dCityDB

### ISSUE THREAD

**Issue by sabahMotamedi** [3dcitydb/importer-exporter#20] opened 2016-12-19 13:35 UTC
Hi,

I'm working on my MSc thesis with topic: "DESIGN AND IMPLEMENTATION A VIRTUAL GLOBE BY WEBGL-BASED FOR 3D CADASTRE" , I have to visualize the 3D cadastre web-based Vitual Globe (Cesium), I install 3dCity-DB Importer Exporter 3.0 and import 3d model in 3dCityDB, But i install 3dCity-DB Importer Exporter 3.3 and 3.3.1 but it not runing. Do you know about this problem?

I have a question, Can i visualize 3d model on the 3dwebclient directly from 3dCityDB (Without import the model in the dae, glTF and etc and store in cloud service)? I don't want to use from the cloud service. Can i it?

Best Regards,
Sabah Motamedi

**Comment by clausnagel** [comment] 2016-12-19 13:45
Please provide more information about the issue with the different versions of the Importer/Exporter. What exactly does not work? Do you receive any error message that you can share? One thing that comes to my mind immediately is that Java 8 is required since version 3.3. Maybe this is the problem?

For a Cesium-based web visualization with the 3dcitydb-web-map framework, you first need to export the data to be visualized as KML or glTF. There is no need to store this data in the cloud though. You can run the web client on your local machine and link the visualization data locally. I think this is also described in the documentation.

**Comment by sabahMotamedi** [comment] 2016-12-19 19:12
I installed 3dcitydb  Importer/Exporter version 3.3 and 3.3.1 on my Laptop but these not running, When i open not running it (Without any error message). 
Thank you the problem solved, Both Java 7 and java 8 installed on my Laptop, I uninstalled java 7 then problem solved,

Can i use from the Geo server Intermediate the 3dcitydb and 3dwebclient for visualization and manager data?

**Comment by sabahMotamedi** [comment] 2016-12-21 14:51
Please response me, Can i visualize a 3d building on the 3dwebclient directly from 3dcitydb without export in glTF and KML format? I want to using from server(Like Geosever) and with WFS visualization a 3d building form 3dcitydb. 
It's so necessary, Please help me, If you can send me a tutorial about it.

Best,
Sabah

**Comment by clausnagel** [comment] 2016-12-21 15:08
Already answered this question for the [3DCityDB-Web-Map-Client](https://github.com/3dcitydb/3dcitydb-web-map) above. If you want to use this client, you need to do an export in KML or glTF first. You could hide the data export behind some web service interface. But you would have to implement this service interface your own.

You can also use the [3DCityDB WFS](https://github.com/3dcitydb/web-feature-service) to query single buildings. Depends on your WFS client whether the response can be visualized right away.

**Comment by jaskiratr** [comment] 2016-12-21 17:18
I've imported cityGML files via 3DCityDB Importer-Exporter. I've also verified the data import through pgAdmin3. 
However, when I export the contents, it exports nothing. I need gltf/kml for cesium 3d tiles. 
```
[12:11:37 INFO] Processed geometry objects: 0
[12:11:37 INFO] Total export time: 00 s.
[12:11:37 INFO] Database export successfully finished.
```

What am I missing? Are there any specific steps involved in exporting the data? 

Thanks,
Jaskirat

**Comment by clausnagel** [comment] 2016-12-21 20:20
The KML/glTF export uses a BBOX filter (unless you provide a list of gml:ids of the features to be exported). Please check the column `ENVELOPE` of the table `CITYOBJECT`. Those tuples having a `NULL` value will not be returned by the BBOX filter and thus not exported. If the column has been populated though, maybe you chose a wrong CRS when setting up the database?

You could try and recalculate all `ENVELOPE` values using the Importer/Exporter tool. Go to the `Database` tab, connect and then click either the button `Recreate all` or `Create missing`.

**Comment by jaskiratr** [comment] 2016-12-23 20:32
That worked! Thanks.

**Comment by clausnagel** [comment] 2017-01-02 17:40
Closing this issue. Feel free to re-open again if the issue has not been resolved.

**Closed by clausnagel** 2017-01-02 17:40 UTC

**Comment by sabahMotamedi** [comment] 2017-01-02 18:15
Hello,
I have a two problems with the Cesium on 3dCity database. 1- When i run the model (building) on the cesium building attributes don't display:" No feature information found".

2- I want to display terrain on the Cesium but i when use from this code there is error: "var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : '//assets.agi.com/stk-terrain/world'
});
viewer.terrainProvider = terrainProvider; "

Thanks a lot,
Sabah

**Comment by sabahMotamedi** [comment] 2017-01-02 18:17
This is a picture from one error:
![error](https://cloud.githubusercontent.com/assets/20692137/21594211/1a071b5c-d135-11e6-8e7f-d1249b15a6c8.jpg)

**Comment by yaozhihang** [comment] 2017-01-02 18:30
Hi Sabah

the display of thematic information on the web client requires a link to an online spreadsheet (Google Fusion Table) which can be easily created by using the Spreadsheet Generator Plugin. More details related to this topic can be found in the 3DCityDB documentation 3.3.0 (Chapter 6 and chapter 8.3.2).

If you want to add the Cesium STK terrain model to the 3D globe, the simplest way is to use the Cesium BaseLayerPicker widget. The corresponding details can be found in the chapter 8.3.4   

best,

Zhihang

**Comment by sabahMotamedi** [comment] 2017-01-02 20:20
Hi Zhihang,

Thank you, Yes i know even when i give it a link of Google Fusion Table link but there is error again and don't display attribute. Look this:

![error](https://cloud.githubusercontent.com/assets/20692137/21595702/274e9a22-d146-11e6-8158-844e5283a7d0.jpg)

**Comment by sabahMotamedi** [comment] 2017-01-02 20:27
I don't want to add own digital terrain model, I want to add a general terrain for world.
Like this in the Cesium site:
![image](https://cloud.githubusercontent.com/assets/20692137/21595797/1ab6865c-d147-11e6-85fa-1ffc1443ec8c.png)

**Comment by yaozhihang** [comment] 2017-01-02 22:28
Please check if the following operating steps were correctly done:
1. Does your generated Google Fusion Table contains a record whose GMLID is equal to "100"? 
2. Have you shared your Google Fusion Table as a public accessible spreadsheet (described on pages 218 to 219 of the 3DCityDB documentation)?.
3. After entering the spreadsheet URL into the text field "thematicDataUrl", have you clicked the button "Save Layer settings" to make this configuration take effect? 

For adding the STK worldwide terrain model, you just need to click the icon button marked with the red box in the following screenshot:
![image](https://dl.dropboxusercontent.com/u/69071139/Clipboard02.jpg)

**Comment by sabahMotamedi** [comment] 2017-01-02 23:12
1- Yes

2- Yes

3- Yes

![image](https://cloud.githubusercontent.com/assets/20692137/21597319/46f2874a-d15e-11e6-9dc1-917c240b01d1.png)

**Comment by sabahMotamedi** [comment] 2017-01-02 23:20
What software you recommend me for create a the City GML model (building)?
I'm using from the Sketchup by citygml plugin but it there a problem and i can't to import citygml format.

**Comment by sabahMotamedi** [comment] 2017-01-03 08:30
It's building sample in tutorial document but don't display attribute it.
Please help me it's for my master thesis.
![error2](https://cloud.githubusercontent.com/assets/20692137/21602695/1669dcd8-d1ac-11e6-8dcc-e8377ea3a379.jpg)

**Comment by yaozhihang** [comment] 2017-01-03 08:59
could you send me the spreadsheet URL of this building sample?

**Comment by sabahMotamedi** [comment] 2017-01-03 11:28
Thank you,
Yes I can, this is: https://fusiontables.google.com/DataSource?docid=1Q5tuP-wMRxrD3ItGsuZsM_JzQy1zDQsFAH-JDEE9#rows:id=1

**Comment by yaozhihang** [comment] 2017-01-03 11:48
please try this spreadsheet URL:
https://fusiontables.google.com/data?docid=1xBofAxFVXI9PVSJo1syTJXI0imjTpA0Zbo2YNntd#rows:id=1

**Comment by sabahMotamedi** [comment] 2017-01-03 17:42
Unfortunately that there is problem still: "No feature information found"

**Comment by sabahMotamedi** [comment] 2017-01-03 19:36
What do i doing for this problem?

**Comment by yaozhihang** [comment] 2017-01-04 09:26
Please also send me your exported KML/glTF models (including the master json file, Tiles folder etc.)

**Comment by sabahMotamedi** [comment] 2017-01-04 12:14
Thank you,
I sent it for you in the zip file.
[New folder.zip](https://github.com/3dcitydb/importer-exporter/files/684572/New.folder.zip)

**Comment by yaozhihang** [comment] 2017-01-04 12:42
I can not reproduce this issue. Everything works fine on my computer. please check the web client link I've careated using your glTF model and spreadsheet

http://www.3dcitydb.org/3dcitydb-web-map/1.1/3dwebclient/index.html?title=3DCityDB-Web-Map-Client&batchSize=3&shadows=false&terrainShadows=false&latitude=35.702629972730286&longitude=51.4264533203925&height=48.967525678313265&heading=25.430448921709925&pitch=-42.16405468243439&roll=0.10581983263361919&layer_0=url%3Dhttps%253A%252F%252Fdl.dropboxusercontent.com%252Fu%252F69071139%252FSabah%252FTehran_Buildings_Layer3_collada_MasterJSON.json%26name%3Dtest%26active%3Dtrue%26spreadsheetUrl%3Dhttps%253A%252F%252Ffusiontables.google.com%252FDataSource%253Fdocid%253D1Q5tuP-wMRxrD3ItGsuZsM_JzQy1zDQsFAH-JDEE9%2523rows%253Aid%253D1%26cityobjectsJsonUrl%3D%26minLodPixels%3D120%26maxLodPixels%3D1.7976931348623157e%252B308%26maxSizeOfCachedTiles%3D200%26maxCountOfVisibleTiles%3D200

**Comment by sabahMotamedi** [comment] 2017-01-04 15:40
This model on your computer works?
I used from your link but it not work. when i use from the data sample it not works again. I think this issue don't relate to my model and likely it is problem of web map client but i don't know what's issue. What do you think?
What do i do?

**Comment by sabahMotamedi** [comment] 2017-01-04 15:42
This is your link result (It's don't works):

![image](https://cloud.githubusercontent.com/assets/20692137/21647959/981b2542-d2b1-11e6-89e7-f9a351e2abc9.png)

**Comment by FxKu** [comment] 2017-01-04 16:03
You could check the web console of chrome. Maybe some request is blocked?

![fetch_attrib_problem](https://cloud.githubusercontent.com/assets/5940260/21648821/a3fb2a2c-d29f-11e6-8ab6-bd7ccbb30984.png)

**Comment by sabahMotamedi** [comment] 2017-01-04 17:00
Thank you very much,
Yes that was, Problem Resolved,

Best Regards,
Sabah

**Comment by yaozhihang** [comment] 2017-01-04 17:15
No, the 3D web map cannot access local Excel files.

**Comment by sabahMotamedi** [comment] 2017-01-08 08:22
Hello,
I want the Cesium read and display attribute of model from model without the fusiontable link.
Can i do it with a code?

Thank you,
Sabah

**Comment by yaozhihang** [comment] 2017-01-08 21:21
A good way is the combined use of the 3dcitydb-web-map and [web feature server](https://github.com/3dcitydb/web-feature-service). You may use the 3DCityDB+WFS as thematic data source which can be easily accessed via HTTP requests.  Unfortunately, the code for this functionality is not open source.  You need to implement this by yourself. However, the JQuery code on the following website could be helpful for you.  
https://github.com/3dcitydb/web-feature-service/blob/master/WebContent/wfsclient/index.html

**Comment by sabahMotamedi** [comment] 2017-01-08 22:27
Hello Yaozhihang,
Thanks a lot,
I don't know how to combine 3dcitydb-web-map with web feature service, Do you have any tutorial?

How to i have to use from JQuery code for this function? 

Please help me this is for my thesis and it's very late.

Thank you,
Sabah

**Comment by yaozhihang** [comment] 2017-01-09 12:11
Sorry, Sabah, i cannot give you further help on this issue. There are no open tutorials or code available.

**Comment by zhangjw5** [comment] 2017-05-04 03:05
Hello, 
       I am writing my graduation thesis, "Based on CityGML 3DGIS Application Studies", I use the 3DCityDB Importer Exporter tool to import my own CityGML data into the 3DCityDB database, but it is wrong to show “Failed to resolve XLink reference '# fme-gen-3010b1e6 -9537-4a87-8e67-f72ebcf0b4f3 '”.
       I feel very depressed, hope we can help me.
Best Regards, ,
Jingwen

**Comment by sabahMotamedi** [comment] 2017-05-04 07:59
Hello,You don't worry, When i work with it i have your error too.Can you import it to 3dcitydb?Maybe you don't set SRID and CRS right or your 3D data coordinate has problem.I attached a few tutorial files for 3DCityDB and etc.Please read these, I hope your problem resolve.
Best,Sabah

**Comment by clausnagel** [comment] 2017-05-04 08:06
This thread has been closed. A new issue #27 has been opened for the question of @zhangjw5. Please use this new thread to provide support. Thanks.

**Comment by zhangjw5** [comment] 2017-05-05 04:12
Thank you ,Sabah,
I think there are some problems with my data, I do not know if it is due to my data without coordinates, I was looking for relevant information.
I have not received your e-mail, can you send me a copy to this mailbox [zhangjingwen423@gmail.com]?
Thank you very much!

**Comment by anwar1010** [comment] 2018-02-18 08:16
When Set Geo-location in SketchUp and then I convert SketchUp file using FME desktop. it cannot add a coordinate system in XML or GML file. Because of the coordinate system, I am unable to import or export data using 3DCity DB importer-exporter
skp2citygml_v1222.2 (backup).zip
this is the FME for SketchUp to XML converter file for lod3.
@clausnagel

**Comment by anwar1010** [comment] 2018-02-18 08:20
when I calculate coordinate system this is the issue
![capture](https://user-images.githubusercontent.com/11944803/36349814-5a844d2c-14ae-11e8-8f95-46bd23ec73d6.PNG)
