### ISSUE TITLE
Failed to Find an ADE extension error 

### ISSUE THREAD

**Issue by alihcsumer** [3dcitydb/importer-exporter#108] opened 2019-12-12 13:34 UTC
Hello, 

I am trying to import GML with importer-exporter version 4.2.0 and db is created by windows shell script in 3dcityDB-4.0.1 "Create_DB.bat"

However getting the error Failed to find an ADE extension for the ADE table 'cityobject'.
[12980.gml.txt](https://github.com/3dcitydb/importer-exporter/files/3955938/12980.gml.txt)

**Comment by yaozhihang** [comment] 2019-12-12 14:05
Hi, i cannot reproduce the error using the standard release version 4.2.0. 
Have you made changes to the source code of the importer-exporter? Have you installed any ADE extensions to the 3DCityDB and importer-exporter?

**Comment by alithegara** [comment] 2019-12-12 15:55
I reinstalled 4.2.0 and create a new db with 4.0.0. did not install ADE plugin manager. No ADE is available. 

![image](https://user-images.githubusercontent.com/5953969/70727419-b74a3f00-1d10-11ea-8383-e893dd8370c2.png)

**Comment by yaozhihang** [comment] 2019-12-12 16:00
Could you install the latest importer-exporter version 4.2.2 https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.2 and test the CityGML-Import once again?

**Comment by alithegara** [comment] 2019-12-13 06:54
managed to import and export with 3.3.1. I will check the differences in schema. Thank you

**Comment by clausnagel** [comment] 2019-12-13 07:29
I downloaded version 4.2.2 of the Importer/Exporter and set up a new 3DCityDB instance using the shell and SQL scripts contained in this version. Afterwards, I successfully imported your dataset. So like @yaozhihang, I couldn't reproduce your error.

Note that your dataset is not completely valid. On the "Import" tab of the Importer/Exporter, you can trigger a schema validation by clicking on "Just validate". This will give you a list of schema validations in your dataset.

**Comment by ZehraKoc91** [comment] 2020-03-04 12:21
Hi,

I am receiving the same error "Failed to find an ADE extension for the ADE table 'cityobject." while importing CityGML data using Importer/Exporter Tool. I am following all the steps successfully given in the tutorial "3DCityDB_V4.0_Hands-On_Tutorial" and as Importer/Exporter, the last release 4.2.2 is the one I have used. It creates a 3dcitydb folder which is creating a 3DCityDB instance via Create_DB.bat and its version is 4.0.2. I have tried older releases of Importer/Exporter and also PostgreSQL database. Still didn't manage to import the given data by the tutorial "Berlin_CityGML_lod2.gml". Would you please help me if any suggestion by your side?

**Comment by yaozhihang** [comment] 2020-03-27 09:27
Hi, @ZehraKoc91 Which PostgreSQL version are you using? which Java version is on you machine?

**Comment by ZehraKoc91** [comment] 2020-03-27 15:08
Hi, Java 8 is on my laptop and the PostgreSQL 12 is the version I have uploaded.

**Comment by yaozhihang** [comment] 2020-04-06 16:28
Hi, today, we've released a new version of 3DCityDB(v4.0.3) and Importer/Exporter(v4.2.3). 
The installer package can be obtained from here: https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3

Could you please do a test with this new version from the scratch? It means that you need to setup a new 3DCityDB instance and install the Importer/Exporter again.

**Comment by mehmetdiramali** [comment] 2020-04-08 10:32
> Hi, today, we've released a new version of 3DCityDB(v4.0.3) and Importer/Exporter(v4.2.3).
> The installer package can be obtained from here: https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3
> 
> Could you please do a test with this new version from the scratch? It means that you need to setup a new 3DCityDB instance and install the Importer/Exporter again.



I have the same problem. I installed newest 3DCityDB(v4.0.3) and Importer/Exporter(v4.2.3). 

> [13:22:19 INFO] Initializing database import...
[13:22:19 INFO] Spatial indexes are enabled.
[13:22:19 INFO] Normal indexes are enabled.
[13:22:19 INFO] Creating list of CityGML files to be imported...
[13:22:19 INFO] List of import files successfully created.
[13:22:19 INFO] 1 file(s) will be imported.
[13:22:20 INFO] Applying XML validation to CityGML input features.
[13:22:20 INFO] Importing file: D:\RTG_Schulungskurs_2016\CityGML-Data\Berlin_CityGML_Lod2.gml
[13:22:20 ERROR] An error occurred: Failed to find an ADE extension for the ADE table 'cityobject'.
[13:22:20 WARN] Aborting import due to errors.
[13:22:20 INFO] Cleaning temporary cache.
[13:22:20 WARN] Database import aborted.

This error still exist. Java version 8 update 241 and PostgreSQL 12.

![Ek Açıklama 2020-04-08 132748](https://user-images.githubusercontent.com/63294840/78774045-c4183000-799c-11ea-907a-2bbf1bfefcba.png)

**Comment by clausnagel** [comment] 2022-02-03 16:24
Closing because this issue cannot be reproduced.

**Comment by selimnar** [comment] 2022-10-12 15:47
Use "-Duser.language=en -Duser.region=US" as JVM parameters to solve this. I recognize some of the users are from Turkey and probably using a Turkish OS system. It is natural thet it can not be replicated of course it is easy to miss locale issues though it is a common one;
Issues cause:
"TableEnum" enum modules "TableEnum fromTableName(String name)" method convert TableEnum.BUILDING enumeration as "buıldıng" instead of "building" preventing to access already existing and non-ADE related table in the database.
Fix: getName method of TableEnum should use the overloaded version of the toLowerCase(java.util.Locale locale) not the zero argument overload
public String getName() {
	return super.toString().toLowerCase(Locale.ENGLISH);
}

**Comment by clausnagel** [comment] 2022-10-12 15:59
@selimnar, thanks, this is very helpful. I had not thought that TableEnum.BUILDING would be turned into "buıldıng" rather than "building". Reopening and labelling as bug.

**Comment by selimnar** [comment] 2022-10-12 16:09
No problem and you are welcome @clausnagel. I have done the same mistake again and again in my software development career and I am sure I will do so again in the future. A very common but easy to miss implementation error. Replication is near impossible, if you are not already using an OS with a locale other than English. Thanks to you and all other contributors for this opensource project by the way and gratitude's for the fast reply as well.

**Comment by clausnagel** [comment] 2022-10-13 13:24
Fixed with 7c3d495272916862cd3243f79d758a9f74129523 (well, hopefully, as I can't test on my machine). I adapted more places in the code where I thought this might be a potential issue.

**Comment by selimnar** [comment] 2022-10-14 07:25
> Fixed with [7c3d495](https://github.com/3dcitydb/importer-exporter/commit/7c3d495272916862cd3243f79d758a9f74129523) (well, hopefully, as I can't test on my machine). I adapted more places in the code where I thought this might be a potential issue.

Same workaround may help with testing "Use "-Duser.language=en -Duser.region=US" as JVM parameters to solve this". Instead use non-US language/region.

**Comment by clausnagel** [comment] 2022-10-14 11:03
Yes, I did this and tested with `-Duser.language=tr` `-Duser.region=TR`. I could reproduce the error in the current release version and could successfully import without errors after 7c3d495272916862cd3243f79d758a9f74129523. So, closing now. Feel free to reopen if the issue still exists.

**Closed by clausnagel** 2022-10-14 11:03 UTC
Labels: bug

**Comment by selimnar** [comment] 2022-10-19 07:46
Just updated the project and run without the "-Duser.language=en -Duser.region=US" JVM parameters using my Turkish OS. I could not replicate the "import" issue.

**Comment by UmutKoca** [comment] 2022-11-28 08:21
I am getting the same error in version 4.3.0. I'm using postgresql 13 on windows 10. Can you check again please?

**Comment by clausnagel** [comment] 2022-11-28 08:49
@UmutKoca, the fix has not been released yet but will be part of the upcoming Importer/Exporter version 5.3.0 (see [changelog](https://github.com/3dcitydb/importer-exporter/blob/master/CHANGES.md)). We are in the final test phase for the release and want to publish it within the next few days.

If you want to test the fix prior to our release, simply clone the Importer/Exporter repository to your local machine and [build](https://github.com/3dcitydb/importer-exporter#building) the tool manually from the `master` branch.

**Comment by UmutKoca** [comment] 2022-11-28 09:07
Thank you @clausnagel

**Comment by iremkapucuoglu** [comment] 2022-11-30 14:29
Hello, I am getting the same error and I saw a suggestion as  "use "-Duser.language=en -Duser.region=US" as JVM parameters "
I couldn't find where to change this parameters. Can you please help?

**Comment by clausnagel** [comment] 2022-11-30 17:55
@iremkapucuoglu, please check [chapter 4.1 of the online user manual](https://3dcitydb-docs.readthedocs.io/en/version-2022.1/impexp/launching.html). It describes how to pass JVM parameters using the `JAVA_OPTS` environment variable. 

We are about to launch the release. It should be available by next week. With this release, the issue should be fixed and no additional JVM parameters should be required.

**Comment by iremkapucuoglu** [comment] 2022-12-01 12:20
Thank you! @clausnagel

**Comment by clausnagel** [comment] 2022-12-15 16:19
@iremkapucuoglu, @UmutKoca we just published the new version: https://github.com/3dcitydb/3dcitydb-suite/releases/tag/v2022.2.0

Please download and test with the new Importer/Exporter. The issue should be gone now and you should not need to adapt JVM parameters.

**Comment by cbsemre** [comment] 2023-11-28 14:38
merhaba.
aynı hatayı alıyorum. sorunu çözdünüz mü ?
