### ISSUE TITLE
3DCityDB-Importer-Exporter-4.3.0-Setup.jar does not install core, only plugins

### ISSUE THREAD

**Issue by jbraese** [3dcitydb/importer-exporter#286] opened 2023-06-02 07:42 UTC
I am trying to install the importer/exporter on Ubuntu 22.04. When I execute `java -jar 3DCityDB-Importer-Exporter-4.3.0-Setup.jar -console` after the license text I am only prompted with options to install the plugins, but not the core 3DCityDatabase. Accepting everything leads to the citydb directory containing only a `plugins` and a `uninstaller` directory, but none of the core functionality

When I install using [3DCityDB-Importer-Exporter-4.2.0-Setup.jar](https://www.3dcitydb.org/3dcitydb/fileadmin/downloaddata/3DCityDB-Importer-Exporter-4.2.0-Setup.jar) everything works as intended, the script gives options to install the core parts, and the corresponding directories are created.

**Comment by yaozhihang** [comment] 2023-06-02 07:55
Hi, could you try the latest version of the importer/Exporter 5.3? The downlod link can be found here:
https://github.com/3dcitydb/3dcitydb-suite/releases/tag/v2022.2.0

**Comment by yaozhihang** [comment] 2023-06-02 08:12
Thanks, i can now also reprodce the problem on Windows OS. OK, I'll look into the problem.

**Comment by yaozhihang** [comment] 2023-06-02 08:55
The problem seems to be in the `standlone-comiler.jar` and occurs sinceImporter/Exporter version 4.3.0. I saw several git changes to that file during the time 2020 November to 2021 January. 
@clausnagel  Do you know which changes have been made?

**Comment by yaozhihang** [comment] 2023-06-05 14:32
Hi @jbraese We looked into the problem. It is not easy to fix, because the issue is in the third-party library "izpack", which we are using for building the installer package. 

The workaround solution is to install the Importer/Exporter using the GUI-Wizard on an Ubuntu Desktop. After that you need to  copy the installation folder to your ubuntu server.

**Comment by clausnagel** [comment] 2023-06-29 18:57
Closing because won't fix. Please use the workaround as described by @yaozhihang

**Closed by clausnagel** 2023-06-29 18:57 UTC

**Comment by SeppBerkner** [comment] 2024-11-18 10:25
I have the same issue on my Mac. With the console only able to install the plugins. WIth the GUI it works fine. Can I use the workaround mentioned by @yaozhihang also if I installed it on my local Mac and then push it to a remote linux server?

**Comment by clausnagel** [comment] 2024-11-18 10:58
> I have the same issue on my Mac. With the console only able to install the plugins. WIth the GUI it works fine. Can I use the workaround mentioned by @yaozhihang also if I installed it on my local Mac and then push it to a remote linux server?

Yes, absolutely. You could also use an unattended installation using an XML configuration file as mentioned [here](https://github.com/3dcitydb/3dcitydb-suite/issues/2) as workaround. But just zipping an installation directory and unzipping it on your destination machine is the simplest workaroung imho.
